### ISSUE TITLE
How to do `ref mut` args?

### ISSUE THREAD

**Issue by Boscop** [bluss/defmac#2]
How can I mark an arg as `ref mut`?
```rust
defmac!(send ref mut slf, msg => { let m = msg; slf.send(m); });
```

I get this error:

![image](https://user-images.githubusercontent.com/535593/43356831-59ab4f66-9278-11e8-91bc-c39500ec4bb0.png)

when trying to call this macro with `self` as first arg in a method that gets `self` as `&mut`.

E.g. `send!(self, Msg::Search(self.search_input.clone()));`

**Comment by bluss** [comment]
There seems to be multiple things going on there, there is no problem with using `ref mut` in general with the macro. In your case you want to borrow self mutably more than once I think?  Because `self` is the first argument to `send!` you will get something that's equivalent to `match self { slf => { ... } }` which borrows self mutably for the whole expression.
